var arrayToObject = require('./utils.js').arrayToObject

const exceptions = {
  blindern: 'på',
  bryne: 'på',
  furuset: 'på',
  geilo: 'på',
  haganes: 'på',
  helgeland: 'på',
  kongsberg: 'på',
  lade: 'på',
  lillehammer: 'på',
  lindås: 'på',
  majorstua: 'på',
  molde: 'på',
  møre: 'på',
  møhlenpris: 'på',
  oppdal: 'på',
  ringerike: 'på',
  rjukan: 'på',
  romerike: 'på',
  røros: 'på',
  sortland: 'på',
  stabekk: 'på',
  steinkjer: 'på',
  storhaug: 'på',
  stovner: 'på',
  toten: 'på',
  tveito: 'på',
  tynset: 'på',
  voss: 'på',
  våland: 'på',
  åland: 'på',
  åndalsnes: 'på',
  ås: 'på',
}

module.exports = arrayToObject(exceptions, 'på')
