"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const utils_1 = require("./utils");
const types_1 = require("./types");
const paaSuffixes = [
    'berg',
    'berget',
    'eggi',
    'eggen',
    'fjell',
    'fjellet',
    'gata',
    'gaten',
    'haug',
    'haugen',
    'kam',
    'kammen',
    'nes',
    'neset',
    'nosi',
    'nut',
    'nuten',
    'plass',
    'plassen',
    'usta',
    'usti',
    'sete',
    'seter',
    'stul',
    'stulen',
    'støl',
    'stølen',
    'sæte',
    'sæter',
    'sætra',
    'såta',
    'toppen',
    'tun',
    'tunet',
    'øy',
    'øya',
    'øyene',
    'ås',
    'åsen',
];
exports.default = utils_1.arrayToObject(paaSuffixes, types_1.Preposision.PÅ);
